inherit_from: .rubocop_todo.yml

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# Cop supports --auto-correct.
Lint/StringConversionInInterpolation:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 165

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 21

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false
